#!/bin/sh

ZORK="/opt/lampp/htdocs/zork/web/zork"
TEMP="/opt/lampp/htdocs/zork/tmp/"
WATCHER="/opt/lampp/htdocs/zork/web/spawnwatch"

if [ $# -ne 0 ]
then
  # we have a session
  # spawn zork
  
  ln -s $ZORK $TEMP$1_zork
  $TEMP$1_zork < $TEMP$1_input > $TEMP$1_output& #2> /dev/null &
  $WATCHER $TEMP$1_zork &
fi
