#!/bin/sh

ZORK="/app/web/zork"
TEMP="/tmp/"
WATCHER="/app/web/spawnwatch"

if [ $# -ne 0 ]
then
   
  ln -s $ZORK $TEMP$1_zork
  $TEMP$1_zork < $TEMP$1_input > $TEMP$1_output& 
  $WATCHER $TEMP$1_zork &
fi
